services:
  bookingdb:
    image: postgres:18.1-alpine
    restart: always
    shm_size: 128mb # Set shared memory size
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
      POSTGRES_DB: bookingdb
    volumes:
      - bookingdata:/var/lib/postgresql/data

volumes:
  bookingdata:
